language: python
python:
  - "3.5"
  - "3.6"
services:
  - postgresql
before_install:
  - pip install pycodestyle codecov
  - python setup.py install
before_script:
  - psql -c 'create database my_db;' -U postgres
  #- psql -f sample_table/schema.sql my_db -U postgres
script:
  - pycodestyle --exclude=venv --ignore=E501 .
  - coverage run --source=. -m pytest
  - coverage report -m
after_success:
  - codecov
